config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :topics do
  	resources :bookmarks, except: [:index] do
      resources :likes, only: [:create, :destroy]
    end
  end

  post :incoming, to: 'incoming#create'

  root to: 'topics#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  has_one :user, through: :topic
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
	has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :topics, dependent: :destroy
  has_many :bookmarks, through: :topics
  has_many :likes, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

	def show
		@bookmark = Bookmark.find(params[:id])
		@topic = Topic.find(params[:topic_id])
	end

	def new
		@topic = Topic.find(params[:topic_id])
		@bookmark = Bookmark.new
		authorize @bookmark
	end

	def create
		@topic = current_user.topics.find(params[:topic_id])
		@bookmark = @topic.bookmarks.new(bookmark_params)
		authorize @bookmark

		if @bookmark.save
			flash[:notice] = "Your bookmark has been saved successfully"
			redirect_to topic_path(@topic)
		else
			flash[:error] = "There was an error, please try again"
			render :new
		end

	end

	def edit
		@bookmark = Bookmark.find(params[:id])
	  @topic = Topic.find(params[:topic_id])
	  # authorize @topic
	  authorize @bookmark
	end

  def update
    @bookmark = Bookmark.find(params[:id])
    @topic = Topic.find(params[:topic_id])
		@user = @bookmark.user
		authorize @topic

    if @bookmark.update_attributes(bookmark_params)
      flash[:notice] = "Your bookmark has been sucessfully updated"
      redirect_to topic_path(@topic)
    else
      flash[:error] = "Error updating, please try again"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @topic

    if @bookmark.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to @topic
    else
      flash[:error] = "There was an error, please try again"
      render :edit
    end
  end

	private

	def bookmark_params
		params.require(:bookmark).permit(:url, :title)
	end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    user = User.find_by(email: params[:sender])

    if user.present?
      topic = Topic.find_or_create_by(user: user, title: params[:subject])
      url = params["body-plain"]
      bookmark = Bookmark.create(topic: topic, url: url)
    end

    head :ok
  end

  private 

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @topic = @bookmark.topic
    like = current_user.likes.build(bookmark: @bookmark)
    
    if like.save
      flash[:notice] = "You have liked the bookmark"
      redirect_to @topic
    else
      flash[:error] = "There was an error, please try again"
    end
  end

  def destroy
    # Get the bookmark from the params
    @bookmark = Bookmark.find(params[:bookmark_id])
    @topic = @bookmark.topic
    # Find the current user's like with the ID in the params
    @like = current_user.likes.where(bookmark_id: @bookmark.id).first

    if @like.destroy
      # Flash success and redirect to @bookmark
      flash[:notice] = "Bookmark unliked"
      redirect_to @topic
    else
      # Flash error and redirect to @bookmark
      flash[:error] = "There was an error, please try again"
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    # @bookmarks = Bookmark.where(@topic.id)
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = current_user.topics.new(topic_params)
    authorize @topic

    if @topic.save
      flash[:notice] = "Topic saved"
      redirect_to root_path
    else
      flash[:error] = "Try again"
      redirect_to new_wiki_path
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.update_attributes(topic_params)
      redirect_to root_path
    else
      flash[:error] = "Error updating, please try again"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to root_path
    else
      flash[:error] = "There was an error, please try again"
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user_bookmarks = @user.bookmarks.find(params[:id])

    @likes = Like.where(user_id: current_user.id)
    # @liked_bookmark = Like.joins(:bookmarks).where(id: bookmark_id)
    @liked_bookmark = Bookmark.includes(:likes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark] do |f| %>
	<%= f.label :url %>
	<%= f.text_field :url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit <%= @bookmark.title %></h1>

<div class="edit-bookmark">
	<%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark } %>

	<% if policy(@bookmark).destroy? %>
	  <%= link_to "delete", [@topic, @bookmark], method: :delete %>
	<% end %>
</div>

app/views/bookmarks/new.html.erb
<h1>Add New Bookmark</h1>

<%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
	<h1>Blocmarks</h1>
		<% if current_user %>
			<div class="welcome">
        Welcome <%= link_to current_user.name, user_path(current_user.id) %>!
			 <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
      </div>
      <div class="button">
        <%= link_to 'Add Topic', new_topic_path %>
      </div>
		<% else %>
			<%= link_to 'Log in', new_user_session_path %>
			<%= link_to 'Sign up', new_user_registration_path %>
		<% end %>
	<nav>
	</nav>
</header>
<body>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% elsif flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/likes/_like.html.erb
<%= bookmark.likes.count %>
<% if like = current_user.liked(bookmark) %>
  <div id="unlike">
    <p>Liked it</p>
    <%= link_to topic_bookmark_like_path(@topic.id, bookmark.id, like.id), class: 'btn btn-primary', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %> 
  </div>
<% else %>
  <div id="like">
    <p>Like me ples!</p>
    <%= link_to topic_bookmark_likes_path(@topic.id, bookmark.id), class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  </div>
<% end %>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'save' %>

<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%= render partial: 'form', locals: { topic: @topic } %>

<div class="button">
  <%= link_to "delete", topic_path, method: :delete, data: { confirm: 'Are you sure?' } %> 
</div>

app/views/topics/index.html.erb
<%= @topics.each do |t| %>
  <h2><%= link_to t.title, topic_path(t.id) %></h2>
  <p><%= t.description %></p>

  <% if policy(t).update? %>
    <%= link_to "edit", edit_topic_path(t.id) %>
  <% end %>

<% end %>

app/views/topics/new.html.erb
<h1>Add New Topic</h1>

<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<div class="new bookmark-link">
  <% if policy(@topic).update? %>
	 <%= link_to "New bookmark", new_topic_bookmark_path(@topic.id) %>
  <% end %>
</div>

<div class="bookmarks">
	<%= @bookmarks.each do |b| %>
    <% if b.title? %>
      <span class="bookmark"><%= b.title %></span>
    <% else %>
		  <span class="bookmark"><%= b.url %></span>
    <% end %>

    <% if current_user %>
      <div class="likes">
        
        <%= render partial: 'likes/like', locals: { bookmark: b } %>
      </div>
    <% end %>

    <% if policy(@topic).update? %>
      <%= link_to "edit", edit_topic_bookmark_path(@topic.id, b.id) %>
    <% end %>

	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= @user_bookmarks.each do |b| %>
  <%= b.url %>
<% end %>

<%= @likes.each do |l| %>
  <%= l.id %>
  <%= l.bookmark_id %>
<% end %>